### PR TITLE
Template templates based on already-defined variables

### PR DESCRIPTION
**Pull request by lucafavatella**

### CODE REVIEW

**Comment by lbischof** [comment]
Thanks! Could you please update changes at the top and add something like: Set user and group via Ansible

This assures that nothing is forgotten when the service files are updated from upstream

**Comment by lucafavatella** [comment]
I see - you mean the changes line. Let me do that.

**Comment by lucafavatella** [comment]
Done. (force-pushed)

**Comment by lbischof** [comment]
:+1:

**Pull request merged**
