### PR TITLE
Add option to globally disable http2 protocol

### PR DESCRIPTION
**Pull request by jgeusebroek**
https://caddyserver.com/docs/cli

Proxy and HTTP2 has some bugs which somethings results in 502 errors. Until this is resolved, easiest option is to disable http2. By default this will have http2 enabled, it only add an option to disable.

More info: https://github.com/mholt/caddy/issues/1080

### CODE REVIEW

**Comment by jgeusebroek** [comment]
Ping :)

**Comment by lbischof** [comment]
Thanks! Looks good. Could you please update the other service files too?

**Comment by jgeusebroek** [comment]
👍  done. Totally forgot about the other ones.

**Comment by lbischof** [comment]
Thanks! And you also corrected the `log_file` Awesome! :+1:

**Pull request merged**
