### PR TITLE
Ensure all templates use certs dir as planted by `tasks/main.yml`

### PR DESCRIPTION
**Pull request by lucafavatella**

### CODE REVIEW

**Comment by lbischof** [comment]
May I ask why you changed CADDYPATH? That is the default value from upstream

**Comment by lucafavatella** [comment]
> edit: ah I see, we create that directory. What speaks against using /etc/caddy and removing it in the tasks?

A user might want to put certs in separate dir than configuration. E.g. I read caddy by default puts it in .caddy subdir of home (off the top of my head). Any default value is ok as long as user of the Ansible role can set certs dir separately.

**Comment by lbischof** [comment]
The reason I am asking is I would like to keep changes to the service files to a minimum, so they stay as close to upstream as possible. I think seperating the config makes sense, so maybe you could try submitting a pullrequest to the Caddy repository?

**Comment by lucafavatella** [comment]
Thanks for warning me - I had another batch of changes in the works and I might have wasted time.
I will see what I shall do with those.

My main aim is parametrizing the role with variables - I doubt I will find time for fixing upstream. I will see.

**Comment by lbischof** [comment]
I have nothing against parameters, but would like to keep the defaults the same as upstream

**Comment by lucafavatella** [comment]
> maybe you could try submitting a pullrequest to the Caddy repository?

PR opened upstream https://github.com/mholt/caddy/pull/1541

**Pull request closed without merging**
