### PR TITLE
Move config from string to file in order to enable templating

### LINKED ISSUE #45: Caddy config passed as path to Jinja2 template rather than caddy_config string variable
In projects I aim at trying to keep as separate repos / branches:
* Applications - including a version of the configuration file templated wrt e.g. domain names, IP addresses, TCP ports;
* Configuration of environments e.g. domain names, IP addresses, TCP ports;
* Application artefacts generation, application configuration template instantiation, provisioning, deployment and acceptance tests.

The current caddy-ansible role takes the Caddyfile as a string in a variable, that makes templating difficult.

Would you welcome a contribution that removes the caddy_config variable and replaces it with a caddy_config_template_path variable? As files not using Jinja2 syntax like `{{ X }}` are templates, such variable would implicitly enable copy of already-instantiated Caddyfile too. Of course the contribution shall update CI test and README.

### PR DESCRIPTION
**Pull request by lucafavatella**
Closes #45.

### CODE REVIEW

**Comment by lbischof** [comment]
Why not leave the old method, if you are renaming the variable anyway? I would have to release a breaking change if we remove `caddy_config`

**Comment by lucafavatella** [comment]
> Why not leave the old method, if you are renaming the variable anyway? I would have to release a breaking change if we remove caddy_config

I was following from the understanding at https://github.com/antoiner77/caddy-ansible/issues/45#issuecomment-291932684

Keeping both would be possible but introduce extra test case. Multiple testing paths are better avoided until CI script supports testing multiple configurations.

Please let me know if you have strong preference and I will try to accommodate (not earlier than 15 days though - busy with other stuff right now).

**Comment by lbischof** [comment]
No problem, I did say you could choose. I'll see what I can do regarding test cases on the weekend.

**Comment by joelnb** [comment]
FWIW I currently use the `caddy_config` variable in a couple of playbooks but using a template would definitely be preferable for my use case because currently I have to put the whole config into vault (because it contains a basic auth password).

**Comment by lucafavatella** [comment]
I plan not to update this anytime soon so closing. Thanks for your review.

**Pull request closed without merging**
