### PR TITLE
Retry downloads

### PR DESCRIPTION
**Pull request by paulfantom**
This should solve issues when server with binaries is unreachable for a moment.

Issues like this: https://travis-ci.org/cloudalchemy/demo-site/jobs/358795052#L774

### CODE REVIEW

**Comment by joelnb** [comment]
This seems like a decent idea & I didn't see any issue but it seems sensible if applying this to some download steps to apply it to all of them. I made commits https://github.com/joelnb/caddy-ansible/commit/01a0835ba9a4c89df4a6949e0b7ad51a52eb01d9 and https://github.com/joelnb/caddy-ansible/commit/156637b1eb3931fcdf2f28c053f07cface09febd to try and cover all of the cases. I haven't tested this yet but will try and do so when I get home.

**Comment by lbischof** [comment]
I also think this is a good idea, but I'm not so sure we should implement it everywhere. I think we should implement it, if a download fails once in a while. @paulfantom did you have problems with the download?

**Comment by paulfantom** [comment]
Yes, I had, output is liked in my previous comment. I'm running this role daily with travis ci and yesterday it failed on caddy download. That's why I added retries to tasks which download file from `caddy_url`.

**Comment by paulfantom** [comment]
Unfortunatelly travis rewrote logs :disappointed: 
Error was due to timeout while trying to download caddy package and it was explicitly stated in logs.

@lbischof ping

**Comment by paulfantom** [comment]
I think that `retries` should be implemented with every task which connects to external service. It means that every `get_url` should get it's own `retries`. It will reduce possible failures due do external services temporary connection problems without affecting performance.

@joelnb this: https://github.com/joelnb/caddy-ansible/commit/156637b1eb3931fcdf2f28c053f07cface09febd#diff-2444ad0870f91f17ca6c2a5e96b26823R15 doesn't make any sense, why trying to retry `copy` module? It won't connect anywhere.

**Comment by lbischof** [comment]
Looks good. Do we really need 10 retries? The default is 3 `retries` with 5 `delay`. I think if it doesn't work 3 times, we can give up. 

Yes, it would be good to have this on every task that connects to an external service

**Comment by paulfantom** [comment]
@lbischof 10 is an arbitrary number, it can be 60 or 3, depends on how long we expect the shortage to be. Remember that this is the **maximum** number of attempts which in normal conditions shouldn't be met.

**Comment by SuperQ** [comment]
I think this was obsoleted by https://github.com/antoiner77/caddy-ansible/pull/82. :grin:

**Pull request closed without merging**
