### PR TITLE
Add flags for systemd capabilites control

### PR DESCRIPTION
**Pull request by SuperQ**
* Bool flag for enable/disable.
* String for list of capabilities to include.

### CODE REVIEW

**Comment by SuperQ** [comment]
Partial help with https://github.com/antoiner77/caddy-ansible/issues/31

**Comment by mikelococo** [comment]
@SuperQ Maybe a readme update documenting the new options and some of the nuances about when their useful vs when you'd want to use setcap instead, possibly including platform support notes:

Ubuntu 16.04 is ok (includes that version of systemd.
Fedora 25 is ok (ships systemd v231 per https://apps.fedoraproject.org/packages/systemd)
RHEL/Cent 7 is not ok (ships systemd v219 per http://mirror.centos.org/centos/7/os/x86_64/Packages/)
Debian Jessie is not ok (ships systemd v215 per https://packages.debian.org/jessie/systemd)

**Comment by SuperQ** [comment]
Sure, I'll add that.

**Comment by SuperQ** [comment]
One note, this isn't about "use this instead of setcap", this is "use this in addition to setcap".  The bug I discovered is that the latest systemd in Debian 9 default restricts capabilities to the point where you need both.

**Comment by SuperQ** [comment]
Updated README.

**Comment by lbischof** [comment]
Thanks :+1:  Would be cool to find out more information about this. Does this always have to be activated when using newer systemd versions? I opened an issue to help track this: #59

**Pull request merged**
