### PR TITLE
Ansible 2 branch

### PR DESCRIPTION
**Pull request by belmarca**
Hey, can you create this branch for me please? I'm making breaking changes for Ansible < 2.0. I don't want to merge into master, but I had no other option for now.

I don't think you can do this easily in GitHub. What you could try is just creating the branch called "ansible_2" with HEAD the same as your master, and then let me do a PR to that branch.

### CODE REVIEW

**Comment by belmarca** [comment]
The build works fine on my system, but it seems it fails here on TravisCI:

```
TASK [caddy-ansible : Extract new Caddy version or build] **********************

skipping: [localhost]

TASK [caddy-ansible : Extract Caddy] *******************************************

skipping: [localhost]
```

So it skips entirely the `unarchive` task. Not sure why, it works on my end.

**Comment by lbischof** [comment]
Thanks, your changes look fine. Is the package module the only breaking
change? I'm not sure how many people can't/haven't updated to ansible 2 and
don't see a great advantage.

It's ok this time but try making multiple pull requests for different stuff
next time (styling etc)

**Comment by belmarca** [comment]
Hi,
You don't need to accept this PR. In fact, I would rather you declined it. I'm just using it for tests. What I would like, if you don't mind, is to get a branch on the main repo for Ansible 2.0 (ansible_2). Then I will separate my changes into multiple PRs.

**Comment by lbischof** [comment]
Sure, I'll create it when I get home.

**Comment by lbischof** [comment]
The travis build is failing because the libcap2-bin package needs to be
installed before the setcap task

**Comment by belmarca** [comment]
Ok, it works now. Again, no rush. If you don't want to make breaking changes, I can keep it in a branch or just fork it altogether. I'm still learning Ansible :+1:

**Comment by lbischof** [comment]
I have created an `ansible_2` branch. I'm not against making breaking changes if discussed properly, but I would like to be backwards compatible with earlier Ansible versions if possible (no package or unarchive without get_url just yet)

**Comment by belmarca** [comment]
I am closing this PR as it is for the wrong branch.

**Pull request closed without merging**
