### PR TITLE
Including rhel based startup script without upstart and add tags to e…

### PR DESCRIPTION
**Pull request by Nitecon**
Created tags for all items so that it can be executed more effectively in large playbooks.

Added a rhel 6 generic init script for minimalist systems that do not have upstart pre-installed

### CODE REVIEW

**Comment by lbischof** [comment]
Thanks for your pullrequest. I'm not quite sure about your logic though... Is there anyway to check if a system is using SysV?

**Comment by Nitecon** [comment]
More likely to check if upstart is installed.  Upstart is not a standard install on RHEL 6 and below it has to be added on manually.  SysV has been standard on RHEL6 and below for a very long time.

**Comment by lbischof** [comment]
Could you see if something like this works? Then we could fallback to sysv if systemd and upstart are not being used.
```
[[ `/sbin/init --version` =~ upstart ]] && echo yes || echo no
```
Got it from here: http://unix.stackexchange.com/a/164092/88089

**Comment by Nitecon** [comment]
so this would work on some later rhel6 (including all amazon linux ami) boxes with the one caveat that it is a very old version of upstart, generally 0.6.5 not like ubuntu with 1.x+ so you gotta take that into account, standard sysv still works on these systems.  On older rhel servers without upstart you get the following:

    [[ `/sbin/init --version` =~ upstart ]] && echo yes || echo no
    /sbin/init: invalid option -- -
    Usage: init 0123456SsQqAaBbCcUu
    no

**Comment by lbischof** [comment]
I think adding a new init system is a good idea, but we should make sure that everything works. I'll try and add centos6 for Vagrant in the next few days so we can test this. Is there any reason you aren't using the official file? https://github.com/mholt/caddy/blob/master/dist/init/linux-sysvinit/caddy

**Comment by Nitecon** [comment]
The official requires *start-stop-daemon* which doesn't exist on every centos by default.  The syvinit I added should even work on ubuntu.

**Comment by lbischof** [comment]
Ok, but I'm still confused. Ubuntu uses Upstart since version 6.10 and Centos/Rhel also use upstart in version 6. Why do you need sysv support instead of using upstart?

I will accept your merge request if you write a better detection command and add a Vagrant machine to test the functionality. I do not want to add hardcoded distribution versions.

**Comment by lbischof** [comment]
Closing because of inactivity

**Pull request closed without merging**
